### ISSUE TITLE
info is stored by (case sensitive) nick rather than nickserv account

### ISSUE THREAD

**Issue by DanielFGray** [TheReverend403/cappuccino#4]
If a user changes their nick to something they have grouped to their nickserv account, ricedb should still be able to retrieve the same information from them, rather than requiring the user to re-input all their info for a different nick.

**Comment by zack6849** [comment]
wen wil u fix this?!11?11!

**Comment by lwatsondev** [comment]
Literally never.

**Comment by DanielFGray** [comment]
@TheReverend403 would you be open to pull requests?

(not that I am in any way implying I will attempt this)

**Comment by lwatsondev** [comment]
Yes.
